config/routes.rb
Wivern::Application.routes.draw do

  resources :tournaments

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  authenticated do
    root :to => 'dashboard#index', as: :dashboard
  end

  root :to => 'landing#index'

  get "/dashboard" => "dashboard#index"

  get 'about' => 'landing#about'
  get 'thanks' => 'landing#thanks'

  get '/league-of-legends' => 'landing#index'
  get '/league-of-legends/about' => 'landing#about'

  

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

	def self.find_for_facebook_oauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_create do |user|
	      user.provider = auth.provider
	      user.uid = auth.uid
	      user.email = auth.info.email
	      user.password = Devise.friendly_token[0,20]
	      user.name = auth.info.name
	      user.image = auth.info.image
	  end
	end

	def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
  	dashboard_path
  end

  def gravatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end
	#<%= image_tag gravatar_url(user) %>
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_user!
	layout "inner"

	#private

	#cannot get image_tag @user.image to work on dashboard so I wanted to permit access to these
	#def user_params
      #params.require(:user).permit!
    #end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
layout "application"
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]
  layout "inner"

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tournament }
      else
        format.html { render action: 'new' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :type, :desc, :image, :game_id, :status, :number_of_players, :number_of_players_limit)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/dashboard/index.html.erb
      <h2 class="sub-header">Dashboard</h2>

    <!--
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
    -->

<script type="text/javascript">
    mixpanel.track("Dashboard Page Loaded")
</script>

app/views/landing/about.html.erb
	<div class="content">

		<h3>Our Vision</h3>

		<p>Our vision is to bring e-sports and professional gaming in a worldwide spotlight, make it a trend. We feel that e-sports should be better, easier to reach and more challenging to all players, not just professional gamers.</p>
		<p>Plan for the future involves building a go-to place for all the competitive gaming happenings in the world. Alongside that, worldwide tournaments in many competitive games, we want to find the best players out there, be they hidden or already on their way to us, and reward them for their skill that is neglected for now.</p>

		<h4>Core values:</h4>
		<ul>
			<li>Providing competitive, high prized and daily challenges to players from any part of the World</li>
			<li>Creating new opportunities for players to bring playing-for-fun to another level, part-time occupation or full-time career choice</li>
			<li>Sustaining and constantly investing back in the gaming community, developers and gaming teams</li>
		</ul>

		<p>Maybe one day e-sports will be considered to be a real sport by everyone, not just by gamers.</p>

		<h4>Legal</h4>
		<p>Team Wivern isn’t endorsed by Riot Games and doesn’t reflect the views or opinions of Riot Games or anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.</p>

	</div>
	
<script type="text/javascript">
    mixpanel.track("About Page Loaded")
</script>

app/views/landing/index.html.erb
	<div class="landing ">
		
		<div class="left">
			<h3>Signup for Early Access</h3>
			<p>We’re building a place for players no matter if they are beginners, semi-pro or a professionals. You can join leagues and tournaments, earn prizes, unlock achievements and discover your true potential!</p>
			<p>We are starting with League of Legends but we have plans to expand in near future.</p>
			<p>We will ensure that you have a great quality competition with lots of remarkable rewards corresponding your abilities.</p>
			<p>Our product is still in development, but we’re organizing special pre-launch tournament for our first 200 members.</p>
			<p>Tournaments are going to starting in ~3 weeks. We’ll have 1v1, 3v3, 5v5 and many more interesting game modes.</p>
			<p><strong>Fill out this short form on the right and get ready!</strong></p>
			<!-- <p>
				<a class="btn twitter" target="_blank" href="http://www.twitter.com/wivernco"><i class="fa fa-twitter"></i>Twitter</a>
				<a class="btn facebook" target="_blank" href="http://www.facebook.com/teamwivern"><i class="fa fa-facebook"></i>Facebook</a>
			</p> -->
		</div>

		<form action="http://plusconf.createsend.com/t/r/s/ttijtud/" method="post" class="right">
			<br><br>
			<!--<h4><span>5</span><span>2</span><span class="slash">/</span><span>1</span><span>0</span><span>0</span> slots left</h4>-->

	        <label>
	      	  <input id="fieldName" name="cm-name" type="text" placeholder="Summoner name" required />
			</label>
			<label>
				<select class="selectpicker" id="fieldjtzkud" name="cm-fo-jtzkud" required>
					<option value="">Server</option>
					<option value="4419957">EU West</option>
					<option value="4419958">EU Nordic &amp; East</option>
					<option value="4419959">North America</option>
		            <option value="4437965">Latin America North</option>
		            <option value="4437966">Latin America South</option>
		            <option value="4437967">Russia</option>
		            <option value="4437968">Turkey</option>
		            <option value="4437969">Brazil</option>
		            <option value="4437970">Oceania</option>
		            <option value="4437971">Republic of Korea</option>
				</select>
       		</label>
       		<div class="multiple">
       			Game mode
				<label>
					<input id="fieldjttydrr-0" name="cm-fo-jttydrr" value="4437563" type="checkbox" />
					<label for="fieldjttydrr-0">1v1 (Solo)</label>
				</label>
				<label>
					<input class="gamemodeteam" id="fieldjttydrr-1" name="cm-fo-jttydrr" value="4437564" type="checkbox" />
					<label for="fieldjttydrr-1">3v3 (I have a team)</label>
				</label>
				<label>
					<input class="gamemodeteam" id="fieldjttydrr-2" name="cm-fo-jttydrr" value="4437565" type="checkbox" />
					<label for="fieldjttydrr-2">5v5 (I have a team)</label>
				</label>
       		</div>
			<label>
        		<input id="fieldEmail" name="cm-ttijtud-ttijtud" type="email" placeholder="E-mail Address" required />
       		</label>
       		<label class="hidden-field">
        		<input id="fieldjttydij" name="cm-f-jttydij" type="text" placeholder="Team name" />
			</label>
       		<label class="button">
		        <button type="submit">Register</button>
			</label>	
		</form>
		
	</div><!-- /container -->

<script type="text/javascript">
    mixpanel.track("Landing Page Loaded")
</script>

app/views/landing/thanks.html.erb
<div class="container group">
	<div class="content">

		<h3>Thank you.</h3>

	</div>
</div><!-- /container -->
	
<script type="text/javascript">
    mixpanel.track("About Page Loaded")
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">

    <%= link_to 'Wivern', root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">

        <%= render 'layouts/navigation_links' %>

    </ul>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Wivern', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>

	<li <% if current_page?(edit_user_registration_path) %>class="active"<% end %>>
		<%= link_to 'Settings', edit_user_registration_path %>
	</li>
	<li <% if current_page?(destroy_user_session_path) %>class="active"<% end %>>
		<%= link_to :logout, destroy_user_session_path, :method => :delete %>
	</li>

<% else %>

	<li <% if current_page?(root_path) %>class="active"<% end %>>
		<%= link_to "Early access", root_path %>
	</li>
	<li <% if current_page?(about_path) %>class="active"<% end %>>
		<%= link_to "About us", about_path %>
	</li>

	<li <% if current_page?(new_user_registration_path) %>class="active"<% end %>>
		<%= link_to 'Create Account', new_user_registration_path %>
	</li>
	<li <% if current_page?(new_user_session_path) %>class="active"<% end %>>
		<%= link_to 'Login', new_user_session_path %>
	</li>

<% end %>

app/views/layouts/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">

    <ul class="nav nav-sidebar">
      <li class="top <% if current_page?(dashboard_path) %>active<% end %>">
        <%= link_to 'Dashboard', dashboard_path %>
      </li>
      <li class="top <% if current_page?(tournaments_path) %>active<% end %>">
        <%= link_to 'Tournaments', tournaments_path %>
      </li>
      <li><a href="">1v1 EUW Weekly Challenger</a></li>
      <li><a href=""><s>1v1 EUW NYE Special</s></a></li>
      <li><a href=""><s>1v1 EUW Trick O' Treat</s></a></li>
      <li><a href="/ladders"><b>Ladders</b></a></li>
      <li><a href="">1v1 EUW</a></li>
      <li><a href="">3v3 EUW</a></li>
    </ul>
   <!--<h5>Quick Links</h5>
    <ul class="nav nav-sidebar">
      <li><a href="">Match Finder</a></li>
      <li><a href="">Recent Matches</a></li>
      <li><a href="">My Team Profile</a></li>
    </ul>-->


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wivern" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Wivern" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <link href="<%= asset_path 'favicon.ico' %>" rel="shortcut icon" type="image/x-icon"/>
    <script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==
  typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);
  b._i.push([a,e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
  mixpanel.init("c7e33c54e356359ab93f801c38529e1c");</script>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
          
        <div class="row">
          <div class="col-sm-9 col-sm-offset-1 col-md-10 col-md-offset-1 main">

            <%= render 'layouts/messages' %>
            <%= yield %>

          </div>
        </div>

        <div class="footer row">
          <div class="container assembly col-sm-9 col-sm-offset-1 col-md-10 col-md-offset-1 main">
            An <span class="img">Assembly</span> project &#8212; <a href="http://www.assemblymade.com/wivern">Contribute now!</a>
          </div>
        </div>
  

      </div>
    </main>

  </body>
</html>

app/views/layouts/backup_application.html.erb
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Wivern &#124; Coming Soon</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
	<script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==
	typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);
	b._i.push([a,e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
	mixpanel.init("c7e33c54e356359ab93f801c38529e1c");</script>
</head>
<body <% if current_page?(about_path) %>class="about"<% end %>>

	<div class="header">
		<div class="container">
			<a href="/"><h1>Wivern</h1></a>
			<ul class="game-picker">
				<li class="active">beta <span class="arrow-up"></span></li>
				<li>Other games...</li>
			</ul>
			<ul class="nav">
					
				<% if user_signed_in? %>

					<li <% if current_page?(dashboard_path) %>class="active"<% end %>>
						<%= link_to 'Dashboard', dashboard_path %>
					</li>
					<li <% if current_page?(edit_user_registration_path) %>class="active"<% end %>>
						<%= link_to 'Settings', edit_user_registration_path %>
					</li>
					<li <% if current_page?(destroy_user_session_path) %>class="active"<% end %>>
						<%= link_to link_to :logout, destroy_user_session_path, :method => :delete %>
					</li>

				<% else %>

					<li <% if current_page?(root_path) %>class="active"<% end %>>
						<%= link_to "Early access", root_path %>
					</li>
					<li <% if current_page?(about_path) %>class="active"<% end %>>
						<%= link_to "About us", about_path %>
					</li>

					<li <% if current_page?(new_user_registration_path) %>class="active"<% end %>>
						<%= link_to 'Create Account', new_user_registration_path %>
					</li>
					<li <% if current_page?(new_user_session_path) %>class="active"<% end %>>
						<%= link_to 'Login', new_user_session_path %>
					</li>

				<% end %>

				
			</ul>
		</div>
	</div>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= yield %>

	<div class="footer">
		<div class="container assembly">
			An <span class="img">Assembly</span> project &#8212; <a href="http://www.assemblymade.com/wivern">Contribute now!</a>
		</div>
	</div>

</body>
</html>

app/views/layouts/inner.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wivern" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Wivern" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <link href="<%= asset_path 'favicon.ico' %>" rel="shortcut icon" type="image/x-icon"/>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">

          <div class="row">
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

             <%= render 'layouts/messages' %>
             <%= render 'layouts/sidebar' %>
             <%= yield %>

            </div>
          </div>

      </div>
    </main>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wivern" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Wivern" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">

         <%= yield %>

      </div>
    </main>
  </body>
</html>

app/views/tournaments/_form.html.erb
<%= form_for(@tournament) do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.number_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :number_of_players %><br>
    <%= f.number_field :number_of_players %>
  </div>
  <div class="field">
    <%= f.label :number_of_players_limit %><br>
    <%= f.number_field :number_of_players_limit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
      <h2 class="sub-header">Tournaments</h2>
        
      <% if false %>
        <%= tournament.type %>
        <%= tournament.desc %>
        <%= tournament.image %>
        <%= tournament.game_id %>
        <%= tournament.status %>
        <%= tournament.number_of_players %>
        <%= tournament.number_of_players_limit %>
        <%= link_to 'Show', tournament %>
        <%= link_to 'Edit', edit_tournament_path(tournament) %>
        <%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>

    <div class="row placeholders">

      <% @tournaments.each do |tournament| %>

      <div class="col-xs-6 col-sm-3 placeholder">
        <img src="http://placehold.it/200x200" class="img-responsive" alt="Generic placeholder thumbnail">
        <h4><%= tournament.name %></h4>
        <span class="text-muted">Something else</span>
      </div>

      <% end %>

    </div>

<br>

<%= link_to 'New Tournament', new_tournament_path %>

app/views/tournaments/new.html.erb
<h1>New tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', tournaments_path %>

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tournament.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @tournament.type %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @tournament.desc %>
</p>

<p>
  <strong>Image:</strong>
  <%= @tournament.image %>
</p>

<p>
  <strong>Game:</strong>
  <%= @tournament.game_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tournament.status %>
</p>

<p>
  <strong>Number of players:</strong>
  <%= @tournament.number_of_players %>
</p>

<p>
  <strong>Number of players limit:</strong>
  <%= @tournament.number_of_players_limit %>
</p>

<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>